"""Tests for rl_env snapshot serialization backends.

Covers:
- EncodedSnapshotBackend round-trip (tar_zst + cas modes).
- FilesystemSnapshotBackend round-trip (tar_zst + cas modes).
- CAS dedup actually shares blobs between snapshots.
- dump_snapshot / load_snapshot cross-process simulation.
- Encoded size < InMemory size on a realistic payload (compression sanity).
- Embeddings round-trip losslessly (float32 precision).
"""

from __future__ import annotations

import os
import sys
import tempfile

import pytest

SRC_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src"))
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

from llm_gateway.rl.rl_env import (  # noqa: E402
    CASBlobStore,
    EncodedSnapshotBackend,
    FilesystemSnapshotBackend,
    InMemorySnapshotBackend,
    MemoryEnv,
    dump_snapshot,
    load_snapshot,
)


class _StubEmbedder:
    """Matches :class:`agent_memory.core.stores.VectorStore` usage:
    - ``embed(texts: list[str]) -> list[list[float]]``  (batch)
    - ``embed_single(text: str) -> list[float]``
    """

    def _one(self, text: str) -> list[float]:
        return [float((hash(text) >> (8 * i)) & 0xFF) / 255.0 for i in range(32)]

    async def embed(self, texts):
        # Support both batch and single-text forms defensively.
        if isinstance(texts, str):
            return self._one(texts)
        return [self._one(t) for t in texts]

    async def embed_single(self, text):
        return self._one(text)


class _StubLLM:
    async def generate(self, *args, **kwargs):  # pragma: no cover
        raise RuntimeError("stub LLM should not be invoked")


async def _populate(env: MemoryEnv) -> None:
    """Write a non-trivial state to the env's stores."""
    fs, vec, graph = env.fs, env.vec, env.graph
    assert fs and vec and graph

    # FS — a few files with varied content so CAS dedup has something
    # to work with.
    fs.write_file("profile/basics.md", "# Basics\n\nUser likes Rust.\n")
    fs.write_file("profile/topics.md", "topics: [rust, systems, distributed]\n")
    fs.write_file("facts/a.md", "A" * 1024)  # larger blob

    # Vec — two collections with embeddings
    vec.create_collection("facts")
    await vec.add("facts", ["fact one", "fact two", "fact three"],
                  [{"src": "u1"}, {"src": "u1"}, {"src": "u2"}])
    vec.create_collection("insights")
    await vec.add("insights", ["insight alpha"], [{"tag": "x"}])

    # Graph
    graph.add_node("user:u1", label="User", properties={"name": "u1"})
    graph.add_node("topic:rust", label="Topic")
    graph.add_edge("user:u1", "topic:rust", relation="learning")


def _fs_state(fs) -> dict[str, bytes]:
    out: dict[str, bytes] = {}
    base = fs.base_path
    for root, _dirs, files in os.walk(base):
        for fn in files:
            p = os.path.join(root, fn)
            rel = os.path.relpath(p, base)
            # .git contents can legally differ in spurious byte details after
            # copy (e.g. pack indices regenerated by later commits). Not used
            # here since we disable git in tests.
            with open(p, "rb") as f:
                out[rel] = f.read()
    return out


def _assert_state_equal(env, expected_fs, expected_vec_counts, expected_node_count):
    # FS
    assert _fs_state(env.fs) == expected_fs

    # Vec — collection sizes + first/last entry fields
    assert {
        name: len(entries) for name, entries in env.vec._collections.items()
    } == expected_vec_counts

    # Graph
    assert len(env.graph._nodes) == expected_node_count


@pytest.mark.asyncio
async def test_encoded_backend_tar_zst_roundtrip():
    with tempfile.TemporaryDirectory() as tmp:
        env = MemoryEnv(
            llm=_StubLLM(), embedder=_StubEmbedder(),
            base_dir=tmp, backend="memory", enable_git=False,
            snapshot_backend=EncodedSnapshotBackend(fs_mode="tar_zst"),
        )
        await env.reset(user_id="u1")
        await _populate(env)

        expected_fs = _fs_state(env.fs)
        expected_vec = {"facts": 3, "insights": 1}
        first_emb = list(env.vec._collections["facts"][0]["embedding"])

        snap = env.snapshot()
        # mutate after snapshot — should be undone on restore
        env.fs.write_file("tmp.md", "dirty")
        await env.vec.add("facts", ["extra"], [{"src": "tmp"}])
        assert "tmp.md" in set(env.fs.list_files())
        assert len(env.vec._collections["facts"]) == 4

        env.restore(snap)
        _assert_state_equal(env, expected_fs, expected_vec, 2)
        restored_emb = list(env.vec._collections["facts"][0]["embedding"])
        # float32 round-trip tolerance
        assert len(restored_emb) == len(first_emb)
        assert max(abs(a - b) for a, b in zip(restored_emb, first_emb)) < 1e-6

        env.close()


@pytest.mark.asyncio
async def test_filesystem_backend_tar_zst_and_cross_process_load():
    with tempfile.TemporaryDirectory() as tmp:
        snap_dir = os.path.join(tmp, "snaps")
        env = MemoryEnv(
            llm=_StubLLM(), embedder=_StubEmbedder(),
            base_dir=os.path.join(tmp, "fs"), backend="memory", enable_git=False,
            snapshot_backend=FilesystemSnapshotBackend(snap_dir, fs_mode="tar_zst"),
        )
        await env.reset(user_id="u1")
        await _populate(env)
        expected_fs = _fs_state(env.fs)

        snap = env.snapshot()
        assert os.path.isfile(snap.payload["path"])
        assert snap.payload["size_on_disk"] > 0

        # simulate "another process": brand-new env + brand-new backend
        # loading the same file
        env2 = MemoryEnv(
            llm=_StubLLM(), embedder=_StubEmbedder(),
            base_dir=os.path.join(tmp, "fs2"), backend="memory", enable_git=False,
            snapshot_backend=FilesystemSnapshotBackend(snap_dir, fs_mode="tar_zst"),
        )
        await env2.reset(user_id="u1")
        attached = env2.snapshot_backend.attach(snap.payload["path"])
        env2.restore(attached)

        assert _fs_state(env2.fs) == expected_fs
        assert len(env2.vec._collections["facts"]) == 3
        assert "topic:rust" in env2.graph._nodes

        env.close()
        env2.close()


@pytest.mark.asyncio
async def test_cas_dedup_reuses_blobs():
    with tempfile.TemporaryDirectory() as tmp:
        snap_dir = os.path.join(tmp, "snaps")
        backend = FilesystemSnapshotBackend(snap_dir, fs_mode="cas")
        env = MemoryEnv(
            llm=_StubLLM(), embedder=_StubEmbedder(),
            base_dir=os.path.join(tmp, "fs"), backend="memory", enable_git=False,
            snapshot_backend=backend,
        )
        await env.reset(user_id="u1")
        await _populate(env)

        # Baseline: take snap1 first so all initial file blobs are in
        # the CAS. CAS dedup effectiveness is measured by the delta
        # between snap1 and snap2.
        snap1 = env.snapshot()
        cas_size_after_first = backend.cas.size()

        # Add one tiny file — most FS content is unchanged, so CAS should
        # grow by roughly the new file's size, NOT the full tree size.
        env.fs.write_file("facts/b.md", "tiny")
        snap2 = env.snapshot()
        cas_size_after_second = backend.cas.size()

        # Both .cbsnap on disk must be tiny compared to the FS content,
        # because the bulk lives in the CAS.
        s1 = snap1.payload["size_on_disk"]
        s2 = snap2.payload["size_on_disk"]
        assert s1 < 5000, f"cbsnap file too large: {s1}"
        assert s2 < 5000, f"cbsnap file too large: {s2}"

        # CAS grew only a little between snapshots (new file <= 100 bytes)
        delta = cas_size_after_second - cas_size_after_first
        assert 0 < delta < 500, f"CAS grew by {delta} bytes; dedup not effective"

        # And both snapshots still restore correctly
        env.fs.write_file("dirty.md", "bad")
        env.restore(snap1)
        assert "facts/b.md" not in set(env.fs.list_files())
        assert "dirty.md" not in set(env.fs.list_files())
        env.restore(snap2)
        assert "facts/b.md" in set(env.fs.list_files())

        env.close()


@pytest.mark.asyncio
async def test_dump_and_load_snapshot_from_any_backend():
    with tempfile.TemporaryDirectory() as tmp:
        # Produce an in-memory snapshot, then dump to .cbsnap, then
        # load via the file-based backend to restore.
        env = MemoryEnv(
            llm=_StubLLM(), embedder=_StubEmbedder(),
            base_dir=os.path.join(tmp, "fs"), backend="memory", enable_git=False,
            snapshot_backend=InMemorySnapshotBackend(),
        )
        await env.reset(user_id="u1")
        await _populate(env)
        expected_fs = _fs_state(env.fs)

        snap = env.snapshot()
        out = os.path.join(tmp, "portable.cbsnap")
        # For InMemory snapshots we must pass live stores so they can
        # be re-encoded.
        dump_snapshot(snap, out, fs=env.fs, vec=env.vec, graph=env.graph)
        # NB: dump_snapshot rewinds stores as a side-effect for
        # InMemory inputs; here stores are already at snap's state, so
        # we can just verify the file lands on disk.
        assert os.path.isfile(out)

        # Now load into a fresh env
        env2 = MemoryEnv(
            llm=_StubLLM(), embedder=_StubEmbedder(),
            base_dir=os.path.join(tmp, "fs2"), backend="memory", enable_git=False,
            snapshot_backend=FilesystemSnapshotBackend(os.path.join(tmp, "snaps2")),
        )
        await env2.reset(user_id="u1")
        loaded = load_snapshot(out)
        env2.restore(loaded)
        assert _fs_state(env2.fs) == expected_fs
        assert len(env2.vec._collections["facts"]) == 3

        env.close()
        env2.close()


@pytest.mark.asyncio
async def test_encoded_size_is_bounded():
    """Sanity: the encoded snapshot size grows roughly with the raw
    payload (FS files + float32 embeddings + graph JSON), *not* with
    the Python-object overhead of a deepcopy.

    Rather than comparing against the deepcopy path (which measures
    on-disk copytree only and therefore massively undercounts the real
    memory footprint), we assert that the encoded size is bounded by a
    simple theoretical upper bound:

        fs_raw_bytes + embeddings_float32_bytes + small_json_overhead

    which would be achieved only if zstd had 0% compression. Anything
    beyond that points at an encoding bug.
    """
    with tempfile.TemporaryDirectory() as tmp:
        env = MemoryEnv(
            llm=_StubLLM(), embedder=_StubEmbedder(),
            base_dir=os.path.join(tmp, "fs"), backend="memory", enable_git=False,
            snapshot_backend=InMemorySnapshotBackend(),
        )
        await env.reset(user_id="u1")

        env.vec.create_collection("big")
        N, DIM = 200, 32
        texts = [f"fact number {i} about topic " + "x" * 40 for i in range(N)]
        await env.vec.add("big", texts, [{"i": i} for i in range(N)])

        fs_bytes_raw = 0
        for i in range(20):
            content = ("# note " + str(i) + "\n") * 50
            env.fs.write_file(f"notes/note_{i}.md", content)
            fs_bytes_raw += len(content.encode())

        enc_backend = EncodedSnapshotBackend(fs_mode="tar_zst")
        enc_snap = enc_backend.capture(env.fs, env.vec, env.graph)
        enc_size = enc_snap.payload["encoded"].size_bytes

        # upper bound (uncompressed, ignoring zstd savings):
        # fs tar + embeddings float32 + text+metadata JSON overhead
        upper_bound = fs_bytes_raw + N * DIM * 4 + N * 200 + 5000
        print(
            f"encoded={enc_size} fs_raw={fs_bytes_raw} "
            f"emb_f32={N * DIM * 4} upper_bound={upper_bound} "
            f"compression={upper_bound / max(enc_size, 1):.2f}x"
        )
        assert enc_size < upper_bound, (
            f"encoded size {enc_size} exceeds naive upper bound {upper_bound}; "
            "serialization likely has overhead bug"
        )

        # Sanity: round-trip still correct on this larger payload
        env.fs.write_file("dirty.md", "bad")
        await env.vec.add("big", ["another"], [{"i": -1}])
        enc_backend.restore(enc_snap, env.fs, env.vec, env.graph)
        assert "dirty.md" not in set(env.fs.list_files())
        assert len(env.vec._collections["big"]) == N

        env.close()


if __name__ == "__main__":  # pragma: no cover
    import asyncio
    asyncio.run(test_encoded_backend_tar_zst_roundtrip())
    asyncio.run(test_filesystem_backend_tar_zst_and_cross_process_load())
    asyncio.run(test_cas_dedup_reuses_blobs())
    asyncio.run(test_dump_and_load_snapshot_from_any_backend())
    asyncio.run(test_encoded_size_is_bounded())
    print("OK")
